courses:
-
  courseData:  tasks/1/courseData.sh
  foreground:  tasks/1/foreground.sh
  task:    tasks/1/task.md
  verify:  tasks/1/verify.sh
-
  courseData:  tasks/2/courseData.sh
  foreground:  tasks/2/foreground.sh
  task:    tasks/2/task.md
  verify:  tasks/2/verify.sh
-
  courseData:  tasks/3/courseData.sh
  foreground:  tasks/3/foreground.sh
  task:    tasks/3/task.md
  verify:  tasks/3/verify.sh
-
  courseData:  tasks/4/courseData.sh
  foreground:  tasks/4/foreground.sh
  task:    tasks/4/task.md
  verify:  tasks/4/verify.sh
-
  courseData:  tasks/5/courseData.sh
  foreground:  tasks/5/foreground.sh
  task:    tasks/5/task.md
  verify:  tasks/5/verify.sh
-
  courseData:  tasks/6/courseData.sh
  foreground:  tasks/6/foreground.sh
  task:    tasks/6/task.md
  verify:  tasks/6/verify.sh
-
  courseData:  tasks/7/courseData.sh
  foreground:  tasks/7/foreground.sh
  task:    tasks/7/task.md
  verify:  tasks/7/verify.sh
